### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by TimelapsedEon** [dzwdz/durability_banks#1]
Ability to add new versions with different fuels, different capacities, and/or different fuel efficiencies via .json

Even config options for same would be appreciated. Love this mod!

**Comment by dzwdz** [comment]
That's a good idea, I will implement it when I'll have some time (probably around the end of this week).

**Comment by TimelapsedEon** [comment]
Woohoo!

**Comment by TimelapsedEon** [comment]
Any way to also have the charger change blockstates, for example "lit" like the blast furnace, while charging? Animated textures while it operates become possible then.

As well as passing a "facing" block state. I'm working on textures for the charger and it's hilariously always pointing north.

**Comment by dzwdz** [comment]
Could you add me on discord so we can talk about the textures? I'm dźwiedź#1420
